version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/python:3.7

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: tox
          command: tox
